// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/passport/passport.proto

package passport

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _passport_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Passport with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Passport) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Passport with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PassportMultiError, or nil
// if none found.
func (m *Passport) ValidateAll() error {
	return m.validate(true)
}

func (m *Passport) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = PassportValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 3 || l > 30 {
		err := PassportValidationError{
			field:  "Name",
			reason: "value length must be between 3 and 30 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PassportValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PassportValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PassportValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PassportMultiError(errors)
	}

	return nil
}

func (m *Passport) _validateUuid(uuid string) error {
	if matched := _passport_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PassportMultiError is an error wrapping multiple validation errors returned
// by Passport.ValidateAll() if the designated constraints aren't met.
type PassportMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PassportMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PassportMultiError) AllErrors() []error { return m }

// PassportValidationError is the validation error returned by
// Passport.Validate if the designated constraints aren't met.
type PassportValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PassportValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PassportValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PassportValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PassportValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PassportValidationError) ErrorName() string { return "PassportValidationError" }

// Error satisfies the builtin error interface
func (e PassportValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPassport.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PassportValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PassportValidationError{}
