name: go-gen-check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:


jobs:
  check-generated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Check if proto or repo files have changed
        id: check-changes
        run: |
          # Check if proto files or repo files have changed
          CHANGED_FILES=$(git diff --name-only HEAD~1)
          if echo "$CHANGED_FILES" | grep -E "(\.proto|internal/repository/passport/repository.go)" > /dev/null; then
            echo "Files changed that require regeneration"
            echo "::set-output name=files_changed::true"
          else
            echo "No relevant files changed"
            echo "::set-output name=files_changed::false"
      
      - name: Generate files if needed
        if: ${{ steps.check-changes.outputs.files_changed == 'true' }}
        run: |
          make proto
          make mocks

      - name: Check if generated files are up to date
        if: ${{ steps.check-changes.outputs.files_changed == 'true' }}
        run: |
          git diff --exit-code ./internal/repository/passport/mock/repository.go
          git diff --exit-code ./internal/pb  # проверка, что файлы protobuf актуальны

      - name: Fail if generated files are not up to date
        if: ${{ steps.check-changes.outputs.files_changed == 'true' }}
        run: |
          if ! git diff --quiet ./internal/repository/passport/mock/repository.go && ! git diff --quiet ./internal/pb; then
            echo "Generated files are out of date. Please run 'make proto' and 'make mocks' to update them."
            exit 1
          fi

      - name: Upload generated files diff
        if: ${{ steps.check-changes.outputs.files_changed == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: generated-files-diff
          path: .
